# Generated by Django 4.1.1 on 2022-10-19 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursestatus',
            name='lessons',
            field=models.ManyToManyField(related_name='lesson_course_status', to='db.lesson'),
        ),
    ]
