# Generated by Django 4.1.1 on 2022-10-03 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('driver_training_center_db', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='course',
            table='course',
        ),
        migrations.AlterModelTable(
            name='lesson',
            table='lesson',
        ),
        migrations.AlterModelTable(
            name='permission',
            table='permission',
        ),
        migrations.AlterModelTable(
            name='role',
            table='role',
        ),
    ]
