# Generated by Django 4.1.1 on 2022-11-23 18:15

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_alter_coursestatus_lessons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursestatus',
            name='is_course_paid',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='coursestatus',
            name='is_internal_practical_exam_passed',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='coursestatus',
            name='is_internal_theoretical_exam_passed',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='coursestatus',
            name='paid_money',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='drivinglicensecategory',
            name='name',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=200)),
        ),
    ]
