# Generated by Django 4.1.1 on 2022-10-03 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver_training_center_db', '0002_alter_course_table_alter_lesson_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drivinglicensecategory',
            name='practice_full_time',
            field=models.DecimalField(decimal_places=0, max_digits=100),
        ),
        migrations.AlterField(
            model_name='drivinglicensecategory',
            name='theory_full_time',
            field=models.DecimalField(decimal_places=0, max_digits=100),
        ),
    ]
