# Generated by Django 4.1.1 on 2022-11-23 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_alter_coursestatus_is_course_paid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drivinglicensecategory',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
