# Generated by Django 4.1.1 on 2022-11-23 18:26

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_alter_drivinglicensecategory_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drivinglicensecategory',
            name='name',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=200)),
        ),
    ]
