# Generated by Django 4.1.1 on 2022-11-23 18:53

from django.db import migrations
import pgcrypto.fields


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0005_alter_drivinglicensecategory_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drivinglicensecategory',
            name='name',
            field=pgcrypto.fields.EncryptedCharField(charset='utf-8', check_armor=True, cipher='aes', versioned=False),
        ),
    ]
