# Generated by Django 4.1.1 on 2022-11-23 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0008_alter_drivinglicensecategory_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drivinglicensecategory',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
