# Generated by Django 4.1.1 on 2022-11-23 19:46

from django.db import migrations
import pgcrypto.fields


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0010_alter_drivinglicensecategory_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drivinglicensecategory',
            name='practice_full_time',
            field=pgcrypto.fields.EncryptedDecimalField(charset='utf-8', check_armor=True, cipher='aes', versioned=False),
        ),
        migrations.AlterField(
            model_name='drivinglicensecategory',
            name='theory_full_time',
            field=pgcrypto.fields.EncryptedDecimalField(charset='utf-8', check_armor=True, cipher='aes', versioned=False),
        ),
    ]
