# Generated by Django 4.1.1 on 2022-11-23 20:13

from django.db import migrations
import pgcrypto.fields


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0013_alter_drivinglicensecategory_practice_full_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='start_date',
            field=pgcrypto.fields.EncryptedDateTimeField(charset='utf-8', check_armor=True, cipher='aes', versioned=False),
        ),
        migrations.AlterField(
            model_name='coursestatus',
            name='paid_money',
            field=pgcrypto.fields.EncryptedDecimalField(charset='utf-8', check_armor=True, cipher='aes', default=0, max_length=6, null=True, versioned=False),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='end_date',
            field=pgcrypto.fields.EncryptedDateTimeField(charset='utf-8', check_armor=True, cipher='aes', versioned=False),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='start_date',
            field=pgcrypto.fields.EncryptedDateTimeField(charset='utf-8', check_armor=True, cipher='aes', versioned=False),
        ),
    ]
